---
# tasks file for host_iso

- name: Install podman
  package:
    name: podman
    state: present
  become: yes

- name: Enable Services (firewalld)
  service:
    name: firewalld
    state: started
    enabled: yes
  become: yes

- name: Open port {{ webserver_port }}/tcp, zone public, for podman container
  firewalld:
    port: "{{ webserver_port }}/tcp"
    permanent: yes
    state: enabled
    zone: "public"
    immediate: yes
  become: yes

- name: Enable samba and samba-client for podman container
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    zone: "public"
    immediate: yes
  loop:
    - "samba"
    - "samba-client"
  become: yes

- name: Start RHCOS image cache container
  containers.podman.podman_container:
    name: webserver
    image: registry.centos.org/centos/httpd-24-centos7:latest
    state: started
    network: host
    volumes:
      - "{{ iso_image_location }}:/var/www/html:z"
  become: yes

- name: Start samba container
  containers.podman.podman_container:
    name: samba_share
    image: dperson/samba
    state: started
    volumes:
      - "{{ iso_image_location }}:/share:z"
    env:
      USERID: 1002
      GROUPID: 64003
    ports:
      - "138:138/udp"
      - "137:137/udp"
      - "445:445"
      - "139:139"
    command: ['-n', '-s', 'share;/share;yes;yes;yes;all;none;none;Shared_files', '-p', '-g', 'usershare allow guests = yes', '-g', 'map to guest = bad user', '-g', 'load printers = no', '-g', 'printcap cache time = 0', '-g', 'printing = bsd', '-g', 'printcap name = /dev/null', '-g','disable spoolss = yes', '-g', 'server min protocol = NT1']

- name: Uploading Discovery ISO to VMware datastore
  include_tasks: vmware.yml
  when: vcenter_datastore is defined

- name: Uploading Discovery ISO to oVirt storage domain
  include_tasks: ovirt.yml
  when: ovirt_storage_domain is defined
