---
# tasks file for host_ovirt_iso
- name: Log in to oVirt
  ovirt_auth:
    url: "{{ ovirt_url | default(omit) }}"
    username: "{{ ovirt_username  | default('admin@internal') }}"
    password: "{{ ovirt_password | default(omit) }}"
    ca_file:  "{{ ovirt_cafile | default(omit) }}"
    insecure: "{{ ovirt_insecure | default(true) }}"
  delegate_to: localhost

- name: Remove virtual machines from oVirt
  ovirt.ovirt.ovirt_vm:
    auth: "{{ ovirt_auth }}"
    name: "{{ hostvars[item]['inventory_hostname'] }}"
    cluster: "{{ ovirt_cluster | default('Default') }}"
    state: absent
    force: true
  with_items:
  - "{{ groups['masters'] }}"
  - "{{ groups['workers'] | default([]) }}"
  delegate_to: localhost
  when: hostvars[item]['vendor'] == 'oVirt'

- name: Remove discovery ISO in {{ ovirt_storage_domain }}
  ovirt.ovirt.ovirt_disk:
    auth: "{{ ovirt_auth }}"
    name: "installer-image.iso"
    storage_domain: "{{ ovirt_storage_domain | default(omit) }}"
    state: absent
  delegate_to: localhost

- name: Upload Discovery ISO to {{ ovirt_storage_domain }}
  ovirt.ovirt.ovirt_disk:
    auth: "{{ ovirt_auth }}"
    name: "installer-image.iso"
    upload_image_path: "{{ iso_image_location }}/installer-image.iso"
    storage_domain: "{{ ovirt_storage_domain | default(omit) }}"
    wait: true
    bootable: true
    format: raw
    content_type: iso
  delegate_to: localhost

- name: Logout from oVirt
  ovirt_auth:
    state: absent
    ovirt_auth: "{{ ovirt_auth }}"
  delegate_to: localhost
...

